Add more tests and update data file
nexB/python-publicsuffix2 pull request #8
Opened 2019-12-19 15:54 UTC by pombredanne

This PR adds tests from the Mozilla test suite for get_tld(strict=True/False) and get_sld()
@hiratara @KnitCode your review is muched welcomed before I push a release!

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

2019-12-19 15:56 UTC, pombredanne commented
Note: Python 2.7 tests are failing for now https://travis-ci.org/nexB/python-publicsuffix2/jobs/627296065?utm_medium=notification&utm_source=github_status

2019-12-19 18:37 UTC, KnitCode commented
> Note: Python 2.7 tests are failing for now https://travis-ci.org/nexB/python-publicsuffix2/jobs/627296065?utm_medium=notification&utm_source=github_status

i think they should pass if the unicode versions are all explicitly converted... i can test later when i get home... but i think replacing 

    def test_get_tld_IDN_labels7(self):
        assert '中国' == publicsuffix.get_tld('www.食狮.中国')

with 
    def test_get_tld_IDN_labels7(self):
        assert u'中国' == publicsuffix.get_tld(u'www.食狮.中国')

should get all of them to work....

2019-12-19 21:42 UTC, KnitCode requested changes
each of the unicode strings has to be replaced with unicode string (wrong term, i'm sure) and the unit tests will pass...
'食狮.com.cn' --> u'食狮.com.cn'

2019-12-19 21:42 UTC, KnitCode commented on tests_mozilla.py
> +        assert 'com.cn' == publicsuffix.get_tld('食狮.com.cn')
each of the unicode strings has to be replaced with unicode string (wrong term, i'm sure) and the unit tests will pass... 
'食狮.com.cn' --> u'食狮.com.cn'

I made the changes locally and all the unit tests passed with that change.

2019-12-20 11:40 UTC, pombredanne commented
@KnitCode Thank you for your review!
I moved to using proper unicode throughout on all Python version in the tests and also made a few other cosmetic fixes and we are all green now.

2019-12-20 14:59 UTC, KnitCode approved these changes
looks good to me!

2019-12-20 15:30 UTC, merged

2019-12-20 15:37 UTC, pombredanne commented
All merged, tagged and pushed as https://pypi.org/project/publicsuffix2/2.20191219/
@hiratara @KnitCode Thank you ++

2019-12-22 06:15 UTC, hiratara commented
Thank you for adding tests. It looks good to me.

It seems a bit weird that no test case produces the same result as test_psl.txt. However, it is natural because we have no function that provides the same effect as check PublicSuffix.